### ISSUE TITLE
There is issue with Pyenchant on Windows-10 64 bit

### ISSUE THREAD

**Issue by JafferWilson** [bishalsainju/personalityPredictionPreprocessing#2]
I am trying to run your repository and the following error I have encountered:  
```
python gfv.py
Traceback (most recent call last):
  File "gfv.py", line 1, in <module>
    import enchant
  File "C:\Python35\lib\site-packages\enchant\__init__.py", line 92, in <module>
    from enchant import _enchant as _e
  File "C:\Python35\lib\site-packages\enchant\_enchant.py", line 102, in <module>
    raise WinError()
OSError: [WinError 193] <no description>
```
Kindly let me know what should I do? I know the error is coming from the repository running on 64-bit OS. PLease help me .

**Comment by SNaveenMathew** [comment]
You must be using Python 64-bit. Switching to 32-bit Python should help. See [this](https://stackoverflow.com/questions/25983908/pyenchant-raises-winerror-193-on-import-using-python-3-3-4) link.

**Comment by JafferWilson** [comment]
I am not able to shift to 32-bit. Is there nothing what I can do to run on the 64-bit system? Kindly, help.

**Comment by SNaveenMathew** [comment]
You may install 32-bit python in 64-bit OS. But if you are stuck with 64-bit python (like me), there is no solution at present.

Since I had no success with PyEnchant, I tried to compile different spell correction libraries (Enchant, aspell, hunspell) for python 3.6 64-bit on Windows but with no success. Here's a summary:
1) These libraries can be installed easily in Linux (32-bit and 64-bit). This is the easiest option. You can use Linux through VMWare.
2) Installing aspell/hunspell on Windows is not straight forward. I managed to install hunspell and set the path, but the library is not able to locate the DLL.
3) You may have to install MinGW to compile the library on Windows. This is not straight forward for a first timer.
4) Compiling using C++ on Windows is not easy.
5) Sometimes 'setup.py' should be updated manually to successfully install the python package.

**Comment by Inadel** [comment]
I have the same problem when i try to lint my code with sublime linter. I don't now how to fix it
